language: android
jdk: oraclejdk8
sudo: required
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-24.0.2
    - android-24
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script:
  - ./gradlew connectedCheck
