language: android
jdk: oraclejdk8
sudo: required
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-24.4.1
    - android-24
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-5be876d5'
    - 'android-sdk-license-c81a61d9'
    - 'google-gdk-license-.+'
script:
  - ./gradlew connectedCheck
