language: android
jdk: oraclejdk8
sudo: required
android:
  components:
    - build-tools-23.0.1
    - android-23
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-5be876d5'
    - 'android-sdk-license-c81a61d9'
    - 'google-gdk-license-.+'
script:
  - echo y | android update sdk --filter platform-tools,build-tools-17.0.0,android-16,extra-android-support,$ANDROID_SDKS --no-ui --force > /dev/null
  - ./gradlew connectedCheck
